### ISSUE TITLE
cannot access devnet in hashscan explorer

### ISSUE THREAD

**Issue by mshakeg** [hashgraph/hedera-local-node#240]
### Description

Previously `devnet` could be selected from the network dropdown in the local hashscan explorer, now it isn't.

### Steps to reproduce

1. Go to local hashscan explorer at: `http://localhost:9090/` and observe no `devnet` in network dropdown; also attempting to go to devnet `http://localhost:9090/devnet/dashboard` redirects to the 404 page i.e. `http://localhost:9090/previewnet/page-not-found`

### Hedera network

other

### Version

@hashgraph/hedera-local@2.3.1

### Operating system

macOS

**Comment by georgi-l95** [comment]
Hey, @mshakeg thanks. This issue is actually with the current hedera-explorer build. I will inform the people responsible to fix this. If you don't want to wait you can use unofficial [build](https://hub.docker.com/layers/glazarov95/hedera-explorer/latest/images/sha256-12b7d69ab21d9b1eda2f6e95de90cca80e4ef96f38a95d64a1e2c6a4ffea5906?context=repo) in the mean time. I will update you and close this issue, when it's fixed.

**Comment by georgi-l95** [comment]
Hey @mshakeg , there is issue with the explorer build not reading the env variables that we are passing. We are working on a fix and will update you, when it's resolved.
