### ISSUE TITLE
Run latest version of Hedera Service

### ISSUE THREAD

**Issue by leric7** [hashgraph/hedera-local-node#28]
### Problem

For now, it's now pulling specific version of all the docker images for grpc, importer, main node, etc.
Can we make sure it's pulling latest version, so that we can have local node running which is exact copy of mainnet/testnet functionality?

### Solution

- Tag the docker images with `latest`, or something, and use it from `docker-compose.yml`

**Comment by SimiHunjan** [comment]
Thanks @leric7. There is some work to do with automation on our end for this. We do plan to have the local node running on the latest version of mainnet.

**Comment by nathanklick** [comment]
@leric7 We have updated the head of the `main` branch to use the same versions deployed to the mainnet environment. The mirror node components have been updated to `v0.57.1` which is two releases ahead of the mainnet environment because the mirror node `v0.57.1` fixes an issue found today and adds relay supports not available in the `v0.56.3` of mirror node.

**Comment by leric7** [comment]
@nathanklick thanks a lot.

**Comment by tmli3b3rm4n** [comment]
Can the note referencing this ticket be removed then?
