### ISSUE TITLE
Add async account creation mode

### ISSUE THREAD

**Issue by georgi-l95** [hashgraph/hedera-local-node#300]
We currently have one way to create accounts, which is sync. This means that when we created accounts at startup, they will assume certain accountId->privateKey mapping. However some people might not care about this mapping, therefore we can mode, which create accounts asynchronous. Which will be way faster than sync mode.
There is already a PR with this change, which was closed. But we can use it for reference.
https://github.com/hashgraph/hedera-local-node/pull/165

**Comment by georgi-l95** [comment]
Hey @mshakeg , I agree that it's slower than hardhat(for example), but around 35 seconds are needed for the consensus image to start and currently from here we can't do anything to speed it up. We are working towards faster local-node, I hope we have some more improvements soon.

**Comment by mshakeg** [comment]
Hey @georgi-l95 good to hear, if you don't mind me asking how exactly are y'all planning on getting the local node to work as fast as other local nodes say hardhat, ganache or foundry? Will any of the functionality currently available on the hedera local node be lost?

**Comment by Nana-EC** [comment]
> Hey @georgi-l95 good to hear, if you don't mind me asking how exactly are y'all planning on getting the local node to work as fast as other local nodes say hardhat, ganache or foundry? Will any of the functionality currently available on the hedera local node be lost?

Hey @mshakeg.
Fair question. We're still in design mode for some of the larger pieces. I can say we don't plan to sacrifice Hedera functionality that is integral to developer operations.
However, since you can't always have it all we are exploring what is most valuable to developers to provide the speed that they are used to from other tools.

Notably, those tools (of which I've also benefited from in the past) all utilize customize EVM's I believe that are in some ways different to the EVM operations on the chains they test against. Also many of those chains do not support system contracts and therefore native services such as HTS and HCS. These are some challenges in getting the design right for the whole range of developer needs we have to consider.

As always we're open to feedback and suggestions as we weigh all angles that will help the community.

**Comment by mshakeg** [comment]
Hey @Nana-EC thanks for the reply.

I think if developers are primarily developing on the HSCS and perhaps using other services via the HSCS(such as HTS or HCS) then they don't even have to use the hedera local node if they are fine with using Foundry(which is quickly becoming the preferred framework for solidity development given its numerous advantages over pretty much all others).

Foundry allows developers to [etch](https://book.getfoundry.sh/cheatcodes/etch?highlight=etch#etch) a contract at a defined address and so the precompile/system contracts at addresses `0x167`, `0x168` and `0x169` can all be mocked using solidity contracts.
