### ISSUE TITLE
Add a container for eth_subscribe 

### ISSUE THREAD

**Issue by Kalina-Todorova** [hashgraph/hedera-local-node#342]
Now that we have support for eth_subscribe we want to add a container for it, relay epic: https://github.com/hashgraph/hedera-json-rpc-relay/issues/889

**Comment by Nana-EC** [comment]
Rather, should we enable both HTTP and web-socket listing on a single container to reduce the memory impact on users?

**Comment by isavov** [comment]
> Rather, should we enable both HTTP and web-socket listing on a single container to reduce the memory impact on users?
It's not really a good option, due to several factors:
1. It would interfere with log monitoring and make it more complex
2. The websocket server is a separate node package, so it would be spawned as a separate node process anyways and Docker memory overhead is negligible (or practically non-existent). If we do it in a single container we would have 1 container consuming about 320 mb of memory, and if we do it as two separate containers we would have 2 containers consuming about 160 mb each.
3. It's a deviation from the production setup.
4. If memory footprint is a concern having them as separate processes is actually better, because one or the other can be disabled.
