### ISSUE TITLE
Provide documentation and examples for running localnode as a shared resource

### ISSUE THREAD

**Issue by pwoosam** [hashgraph/hedera-local-node#401]
### Problem

A localnode on my machine is not a shareable resource. Localnode needs to become a shareable resource for stakeholders, other developers, and beta users to use my dapp.

### Solution

- Deploy localnode to a cloud provider
- Deploy hashscan to a cloud provider and configure hashscan to point to localnode's mirror node
- Configure firewall rules in cloud provider
- Configure hashgraph/sdk to connect to localnode
- Provide documentation and examples for doing the above
- Make this process easy to deploy and configure localnode, hashscan, and hashgraph/sdk

**Comment by rbair23** [comment]
I love this issue.

In our own testing, we use a tool called FST for "full stack test". We're rebuilding it from its first version (which was known as JRS). The FST comes in several parts:

1. A library for lifecycle management of a cluster. It comes with GCP support out of the box. You give it some credentials to your GPC and it will create all the nodes and install all the software, then you can run all your tests or leave it up indefinitely, and use FST to take it down when you're done. Or perform an upgrade. We're adding in everything into this -- hashscan, hashio, mirror node, consensus node, proxies, uploaders, etc. And you can integrate it with a running grafana / loki instance to get all the metrics information. You get to choose how many nodes, you get to choose what kind of nodes (cheap, or mainnet like). Anybody in the world can use this to spin up a network at any time they want, and tear it down again at the end.
2. A library integrated with JUnit for running tests. This is extremely useful for us, because we're in Java. 

We use this tool on every build (for example, see #9103. You can see the "JRS" build at the bottom).

Local node is much less expensive to operate and good for single-node deployment. But FST might be a better fit for creating nodes. You can see the project here: https://github.com/hashgraph/full-stack-testing

**Comment by georgi-l95** [comment]
> Local node is much less expensive to operate and good for single-node deployment. 

Not only single-node, it supports multi-node with up to 4 nodes.

**Comment by Nana-EC** [comment]
Thanks @pwoosam 
Great suggestion and in line with ideas we've had.
In addition to the above some initial steps we feel that will help will come from efforts such as https://github.com/hashgraph/hedera-local-node/issues/189
In this case users could easily deploy local node to k8s envs in any cloud provider and share it as needed as well as configure many of the items you noted.

**Comment by yaroslav-007** [comment]
You can achieve this by running the repo in codespace/gitpod integration.

After the local node is up you should, in order to make Hedera Explorer accessible, make ports 8080 and 5551 public via the web interface:

 - for codespace: https://docs.github.com/en/codespaces/developing-in-a-codespace/forwarding-ports-in-your-codespace#sharing-a-port
 - for gitpod: https://www.gitpod.io/docs/configure/workspaces/ports#default-port-behaviors

After that edit in the `.env` file the variable `DOCKER_LOCAL_MIRROR_NODE_URL` to point to the URL address showed in codespace/gitpod. It is usually in the following format:

 - for codespace: https://${CODESPACE_NAME}-5551.app.github.dev
 - for gitpod: https://5551-${HOSTNAME}.${GITPOD_WORKSPACE_CLUSTER_HOST}

 and restart the local node with `hedera restart -d`.

You can also consider making public the following exposed ports:

| Type                              | Endpoint                                         |
| --------------------------------- | ------------------------------------------------ |
| Consensus Node Endpoint           | [http://localhost:50211](http://localhost:50211) |
| Mirror Node GRPC Endpoint         | [http://localhost:5600](http://localhost:5600)   |
| Mirror Node REST API Endpoint     | [http://localhost:5551](http://localhost:5551)   |
| JSON RPC Relay Endpoint           | [http://localhost:7546](http://localhost:7546)   |
| JSON RPC Relay Websocket Endpoint | [http://localhost:8546](http://localhost:8546)   |
| Mirror Node Explorer              | [http://localhost:8080](http://localhost:8080)   |
| Grafana UI                        | [http://localhost:3000](http://localhost:3000)   |
| Prometheus UI                     | [http://localhost:9090](http://localhost:9090)   |




Please review also the following project: [Solo](https://github.com/hashgraph/solo)
