### ISSUE TITLE
Localnode fails in many Hedera smart-contracts' CI jobs

### ISSUE THREAD

**Issue by quiet-node** [hashgraph/hedera-local-node#534]
### Description

Recently, I observed that Localnode often fails to start up, but only within the CI environment; it functions perfectly when executed locally. The failure is accompanied by the following error message:

```
[Hedera-Local-Node] ERROR (ConnectionService) connect ECONNREFUSED 127.0.0.1:5600
[Hedera-Local-Node] TRACE (ConnectionService) Waiting for the containers at 127.0.0.1:5600, retrying in 0.1 seconds...
```

For reference, an example can be found at https://github.com/hashgraph/hedera-smart-contracts/actions/runs/7760468776/job/21166781788?pr=661#step:9:68

### Steps to reproduce

Run a CI job in the Hedera Smart Contract repo

### Hedera network

other

### Version

latest

### Operating system

None

**Comment by yaroslav-007** [comment]
Hello @quiet-node ,

I have found that the error comes from https://github.com/hashgraph/hedera-local-node/blob/a60cf38308796057ad67891651bbe4abb0cea808/src/services/ConnectionService.ts#L75-L100 which is basically a check if a connection could be made to `address:port`. I have confirm this by preventing the deployment of the containers and observed the error messages.

I have cloned the repo into private one and have run github action workflow in self hosted system, in order to be able to investigate further. Unfortunately I was not able to hit the problem.

Also checked `hedera-json-rpc-relay` latest runs and was not able to spot recent failure.

Do you still experience the described behavior ?

Thanks
