### ISSUE TITLE
Docker.sock check fails for certain environments

### ISSUE THREAD

**Issue by michielmulders** [hashgraph/hedera-local-node#537]
### Description

When starting the Hedera local node using `hedera start -d` or `npm run start -- -d` (after installing deps), it throws an error `Docker is not running`. The error is thrown by the Dockerservice, at this line of code: https://github.com/hashgraph/hedera-local-node/blob/75cf9612df57c1f4082429bd9be47c1ef002acc9/src/services/DockerService.ts#L71

```js
const defaultSocketPath = IS_WINDOWS
        ? '//./pipe/docker_engine'
        : '/var/run/docker.sock';

        this.dockerSocket = process.env.DOCKER_SOCKET || defaultSocketPath;
```

However, it appears that new Docker versions for Mac environments (I have M1 chip) don't create the symlink to `/var/run/docker.sock`. You can find a thread about it [here](https://forums.docker.com/t/is-a-missing-docker-sock-file-a-bug/134351). However, when installing Docker, it still creates this `docker.sock` file in your home dir under: `~/.docker/run/docker.sock`

After adding a symlink manually, the `hedera start -d` command works: `sudo ln -s $HOME/.docker/run/docker.sock /var/run/docker.sock`

Therefore, I suggest updating the `checkDocker` to check both Docker paths (`/var/run` and `~/.docker/run`): https://github.com/hashgraph/hedera-local-node/blob/75cf9612df57c1f4082429bd9be47c1ef002acc9/src/services/DockerService.ts#L105 

### Steps to reproduce

hedera start -d

### Hedera network

other

### Version

v2.18.0

### Operating system

macOS

**Comment by yaroslav-007** [comment]
Hello,

I am currently testing this bug on Mac with M3 chip. As I check I had already created symlink:
`lrwxr-xr-x  1 root  daemon  48 Jan  3 11:12 /var/run/docker.sock -> /Users/yaroslav/.docker/run/docker.sock`

As you mention `new Docker versions` and since I didn't had the last one, I removed link `/var/run/docker.sock` and reinstalled Docker Desktop with the latest one (from https://www.docker.com/products/docker-desktop/).

I noticed the following error message :

![Screenshot 2024-02-06 at 11 17 46](https://github.com/hashgraph/hedera-local-node/assets/43340595/47af0df3-baa4-4e95-86b9-6904837ee18d)

When I `Re-applied configurations`  the symlink was auto-created:
`ls -al /var/run/docker.sock
lrwxr-xr-x  1 root  daemon  48 Feb  6 11:17 /var/run/docker.sock -> /Users/yaroslav/.docker/run/docker.sock`

As I have checked further in [Release Notes](https://docs.docker.com/desktop/release-notes/):
 - In version [4.25.0](https://docs.docker.com/desktop/release-notes/#4250) there is fix titled `Fixed a bug where Re-apply configuration might not work when /var/run/docker.sock is mis-configured.`
  - In version [4.14.0](https://docs.docker.com/desktop/release-notes/#4140) there is fix titled `Fixed an issue that prevented the creation of Dev Environments on new Mac installs (error "Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?").`
  
I believe during installation normally `/var/run/docker.sock` is linked to `~/.docker/run/docker.sock`. Could we check if there is anything specific to your installation/version of Docker ?

**Comment by michielmulders** [comment]
@yaroslav-007 Here are my env details:

- Apple M1, 16GB ram, v13.4 (22F66)
- Docker version 25.0.2, build 29cf629
- Docker Compose version v2.24.3-desktop.1
- NPM v10.2.3
- Node v20.10.0

I also reinstalled Docker and had the same issue: the symlink didn't exist. What else do you think can cause this? Would it be possible to add an extra message to the error perhaps to instruct the reader to verify if they have this symlink and if not, they should create it instead of just telling "Docker is not running" while the Docker engine is running?

Thanks!

**Comment by yaroslav-007** [comment]
Hi @michielmulders 

Could we also sync on the steps you are using for the installation/reinstallation (e.g. using the `brew` tool or installation file  etc.)?

**Comment by michielmulders** [comment]
@yaroslav-007 
I'm using the Docker .dmg download from the official website: https://www.docker.com/get-started/ (for Mac Apple chip).
I just install the Docker.dmg file in my applications folder, which is default. Other than that, I don't do anything :)

Thanks. Hope this helps.

**Comment by yaroslav-007** [comment]
Hello @michielmulders 

Could you please check from Docker Desktop app in the `Advanced`  tab on the right, if `Allow the default Docker socket to be used (requires password)` is enabled. [More Info](https://docs.docker.com/desktop/mac/permission-requirements/#installing-symlinks)

![Screenshot 2024-02-07 at 15 21 54](https://github.com/hashgraph/hedera-local-node/assets/43340595/a5a495f0-7280-4d7a-9705-f889aed3e591)

As I tested toggling this option removes/creates `/var/run/docker.sock` symlink.

**Comment by michielmulders** [comment]
@yaroslav-007 Nope, I was missing this option indeed. I'll create a PR in Hedera's docks to make sure to document this option which resolves all problems. 

I removed the manual symlink and then applied the option, applied + restarted Docker Desktop, and now the docker.sock file exists in my /var/run/ folder.

**Comment by yaroslav-007** [comment]
Hello,

Thanks for the response.
